<?php
/**
 * Created by PhpStorm.
 * User: liuyifan
 * Date: 30/11/17
 * Time: 下午 05:52
 */

namespace app\modules\mihuwai;


use yii\base\Module;

class MihuwaiModule extends Module
{
    public $controllerNamespace = 'app\modules\mihuwai\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}